(dp1
S'output'
p2
S"<type 'exceptions.AttributeError'> 'DAL' object has no attribute 'nome'"
p3
sS'layer'
p4
S'/home/leonardo/Downloads/web2py/applications/KidsAppManager/controllers/default.py'
p5
sS'code'
p6
S'<code object <module> at 0x7f8fd42eb230, file "/home/leonardo/Downloads/web2py/applications/KidsAppManager/controllers/default.py", line 10>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/leonardo/Downloads/web2py/gluon/restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "/home/leonardo/Downloads/web2py/applications/KidsAppManager/controllers/default.py", line 177, in <module>\n  File "/home/leonardo/Downloads/web2py/gluon/globals.py", line 419, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/leonardo/Downloads/web2py/applications/KidsAppManager/controllers/default.py", line 156, in busca_aluno\n    freq_campo = db(db.frequencia.cod_presenca).select(\'nome.nome_crianca\')\n  File "/home/leonardo/Downloads/web2py/gluon/packages/dal/pydal/objects.py", line 2249, in select\n    fields = adapter.expand_all(fields, tablenames)\n  File "/home/leonardo/Downloads/web2py/gluon/packages/dal/pydal/adapters/base.py", line 170, in expand_all\n    append(self.db[tablename][fieldname])\n  File "/home/leonardo/Downloads/web2py/gluon/packages/dal/pydal/base.py", line 662, in __getitem__\n    return self.__getattr__(str(key))\n  File "/home/leonardo/Downloads/web2py/gluon/packages/dal/pydal/base.py", line 669, in __getattr__\n    return BasicStorage.__getattribute__(self, key)\nAttributeError: \'DAL\' object has no attribute \'nome\'\n'
p11
s.