(dp1
S'output'
p2
S"<type 'exceptions.AttributeError'> 'Field' object has no attribute 'nome_crianca'"
p3
sS'layer'
p4
S'/home/leonardo/Downloads/web2py/applications/KidsAppManager/controllers/default.py'
p5
sS'code'
p6
S'<code object <module> at 0x7fc0e4446630, file "/home/leonardo/Downloads/web2py/applications/KidsAppManager/controllers/default.py", line 10>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/leonardo/Downloads/web2py/gluon/restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "/home/leonardo/Downloads/web2py/applications/KidsAppManager/controllers/default.py", line 193, in <module>\n  File "/home/leonardo/Downloads/web2py/gluon/globals.py", line 419, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/leonardo/Downloads/web2py/applications/KidsAppManager/controllers/default.py", line 175, in busca_aluno\n    print db(db.frequencia.cod_presenca == cod_presenca).select(db.frequencia.id, db.frequencia.nome.nome_crianca)\nAttributeError: \'Field\' object has no attribute \'nome_crianca\'\n'
p11
s.