(dp1
S'output'
p2
S"<type 'exceptions.KeyError'> "
p3
sS'layer'
p4
S'/home/leonardo/Downloads/web2py/applications/KidsAppManager/controllers/default.py'
p5
sS'code'
p6
S'<code object <module> at 0x7f04d0046f30, file "/home/leonardo/Downloads/web2py/applications/KidsAppManager/controllers/default.py", line 10>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/leonardo/Downloads/web2py/gluon/restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "/home/leonardo/Downloads/web2py/applications/KidsAppManager/controllers/default.py", line 201, in <module>\n  File "/home/leonardo/Downloads/web2py/gluon/globals.py", line 419, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/leonardo/Downloads/web2py/applications/KidsAppManager/controllers/default.py", line 190, in frequencia\n    form = SQLFORM(db.cadastro, record, deletable=True)\n  File "/home/leonardo/Downloads/web2py/gluon/sqlhtml.py", line 1464, in __init__\n    default = record[fieldname]\n  File "/home/leonardo/Downloads/web2py/gluon/packages/dal/pydal/objects.py", line 96, in __getitem__\n    raise KeyError\nKeyError\n'
p11
s.